### Aggregation and statistics

In [ ]:
# paprasti statistiniai skaičiavimai
df["Kaina"].sum()     # suma
df["Kaina"].mean()    # vidurkis
df["Kaina"].min()     # mažiausia reikšmė
df["Kaina"].max()     # didžiausia reikšmė
df["Kaina"].median()  # mediana
df["Kaina"].std()     # standartinis nuokrypis

df.describe() # greita santrauka

In [ ]:
# groupby() yra viena iš galingiausių pandas funkcijų, leidžianti grupuoti duomenis pagal vieną ar 
# kelis stulpelius ir atlikti agregacijas, pvz., suskaičiuoti, susumuoti, gauti vidurkį ir pan.

df.groupby("Stulpelis")["Kitas_Stulpelis"].funkcija()

# Pavyzdys
import pandas as pd

df = pd.DataFrame({
    "Miestas": ["Vilnius", "Kaunas", "Vilnius", "Kaunas", "Klaipėda"],
    "Pardavimai": [100, 200, 150, 120, 130]
})

# Grupavimas pagal miestą ir pardavimų vidurkio skaičiavimas
result = df.groupby("Miestas")["Pardavimai"].mean()
print(result)
# Rezultatas
Miestas
Kaunas      160.0
Klaipėda    130.0
Vilnius     125.0
Name: Pardavimai, dtype: float64

# Grupavimas pagal "Miestas" ir skaičiuojamas vidurkis bei suma
result = df.groupby("Miestas")["Pardavimai"].agg(["mean", "sum", "count"])
print(result)
# Rezultatas
           mean  sum  count
Miestas                    
Kaunas     160   320      2
Klaipėda   130   130      1
Vilnius    125   250      2

# Pavyzdys: Grupavimas pagal kelis stulpelius
df = pd.DataFrame({
    "Miestas": ["Vilnius", "Vilnius", "Kaunas", "Kaunas", "Klaipėda"],
    "Prekė": ["A", "B", "A", "B", "A"],
    "Kiekis": [5, 3, 8, 6, 2]
})

result = df.groupby(["Miestas", "Prekė"])["Kiekis"].sum()
print(result)
# Rezultatas
Miestas   Prekė
Kaunas    A        8
          B        6
Klaipėda  A        2
Vilnius   A        5
          B        3
Name: Kiekis, dtype: int64

In [ ]:
#Funkcija agg() (aggregate) leidžia vienu metu pritaikyti kelias skirtingas funkcijas prie duomenų, kai naudojamas groupby().
# Tai ypač naudinga, kai nori, pavyzdžiui, ir vidurkį, ir suma, ir skaičių gauti vienoje lentelėje.

# Dažniausiai naudojamos funkcijos:
# Funkcija	- Reikšmė
# "sum"	- Suma
# "mean" - Vidurkis
# "min"	- Mažiausia reikšmė
# "max" - Didžiausia reikšmė
# "count" -	Elementų skaičius
# "nunique" - Unikalių reikšmių skaičius
# "median" - Mediana
# "std"	- Standartinis nuokrypis
# "var"	- Dispersija
# "first" - Pirma reikšmė
# "last" - Paskutinė reikšmė

#  Galima naudoti ir savo funkcijas
df.groupby("Miestas")["Pardavimai"].agg(lambda x: x.max() - x.min())

#Pavyzdys
import pandas as pd

df = pd.DataFrame({
    "Miestas": ["Vilnius", "Kaunas", "Vilnius", "Kaunas", "Klaipėda"],
    "Pardavimai": [100, 200, 150, 120, 130]
})

# Grupavimas pagal Miestas ir kelių funkcijų taikymas Pardavimai stulpelyje
rezultatas = df.groupby("Miestas")["Pardavimai"].agg(["mean", "sum", "count"])
print(rezultatas)

# Rezultatas
           mean  sum  count
Miestas                     
Kaunas     160   320      2
Klaipėda   130   130      1
Vilnius    125   250      2

#####

df = pd.DataFrame({
    "Miestas": ["Vilnius", "Kaunas", "Vilnius", "Kaunas", "Klaipėda"],
    "Pardavimai": [100, 200, 150, 120, 130],
    "Darbuotojai": [5, 6, 7, 5, 4]
})
rez = df.groupby("Miestas").agg({
    "Pardavimai": ["sum", "mean"],
    "Darbuotojai": ["max", "min"]
}
print(rez)

# Rezultatas
                                           Pardavimai         Darbuotojai     
                  sum  mean         max  min
Miestas                                    
Kaunas            320  160.0           6    5
Klaipėda          130  130.0           4    4
Vilnius           250  125.0           7    5